### ISSUE TITLE
Skip non-image file types

### ISSUE THREAD

**Issue by wadebarrie** [victordomingos/optimize-images#16]
Script crashes when it tries to process .pdf files in same folder as .jpg or .png - would be nice if it would just skip these and carry on.

`The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\wbarrie\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\wbarrie\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\wbarrie\AppData\Local\Programs\Python\Python37\Scripts\optimize-images.exe\__main__.py", line 7, in <module>
  File "c:\users\wbarrie\appdata\local\programs\python\python37\lib\site-packages\optimize_images\__main__.py", line 97, in main
    for r in executor.map(do_optimization, tasks):
  File "c:\users\wbarrie\appdata\local\programs\python\python37\lib\concurrent\futures\process.py", line 483, in _chain_from_iterable_of_lists
    for element in iterable:
  File "c:\users\wbarrie\appdata\local\programs\python\python37\lib\concurrent\futures\_base.py", line 598, in result_iterator
    yield fs.pop().result()
  File "c:\users\wbarrie\appdata\local\programs\python\python37\lib\concurrent\futures\_base.py", line 428, in result
    return self.__get_result()
  File "c:\users\wbarrie\appdata\local\programs\python\python37\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
PIL.UnidentifiedImageError: cannot identify image file './danby\\refrigerators-and-freezers\\DCR031B1BSLDD\\DCR031B1BSLDD-product-specs.jpg'` <- this is actually a .pdf

**Comment by victordomingos** [comment]
The was a [recent change](https://github.com/victordomingos/optimize-images/blob/0907934727f7298c4b009fc2e00b9218785af392/optimize_images/__main__.py#L65)  regarding that behaviour in one of the last few commits. So, the current development version you can download from GitHub should behave properly. The PyPI.org version still doesn't reflect that change. Would you be able and willing to [test with the current version from this repository in GitHub](https://github.com/victordomingos/optimize-images/blob/master/docs/docs_EN.md#installing-the-most-recent-development-version-may-be-unstable)?

I also have in my plans to experiment with [imghdr.what()](https://github.com/victordomingos/optimize-images/issues/15). It's in the standard library, so maybe it can be useful, even though I remember having read somewhere about it being buggy. That's something that I want to test, to see if it is of any help.

**Comment by wadebarrie** [comment]
Hi Victor,

Thanks a lot for the message - I will give the current version a shot!

Thanks,
Wade

**Comment by victordomingos** [comment]
Ok. If you do, please come back to report wether that solved this issue for you.

**Comment by victordomingos** [comment]
Updated on PyPI.
